package aa:packet;

interface types {
    enum proxy-type {
        head-unit,
        mobile-device,
    }

    record modify-context {
        sensor-channel: option<u8>,
        nav-channel: option<u8>,
        audio-channels: list<u8>,
    }

    record packet {
        proxy-type: proxy-type,
        channel: u8,
        packet-flags: u8,
        final-length: option<u32>,
        message-id: u16,
        payload: list<u8>,
    }

    record config-view {
        audio-max-unacked: u32,
        remove-tap-restriction: bool,
        video-in-motion: bool,
        developer-mode: bool,
        ev: bool,
        waze-lht-workaround: bool,
    }

    record custom-config-entry {
        name: string,
        typ: string,
        description: string,
        default-value: string,
        values: option<list<string>>,
    }

    record custom-config-section {
        title: string,
        values: list<custom-config-entry>,
    }

    enum decision {
        forward,
        drop,
    }
}

interface host {
    use types.{packet};

    replace-current: func(pkt: packet);
    send: func(pkt: packet);
    info: func(msg: string);
    error: func(msg: string);
    send-ws-event: func(topic: string, payload: string) -> bool;
    rest-call: func(method: string, path: string, body: string) -> string;
    rest-call-async: func(method: string, path: string, body: string) -> string;
    rest-result-topic: func() -> string;
    get-config: func(name: string) -> option<string>;
}

world packet-hook {
    use types.{modify-context, packet, config-view, custom-config-section, decision};

    import host;

    export on-create: func();
    export on-destroy: func();
    export custom-configs: func() -> list<custom-config-section>;
    export on-config-changed: func(name: string, value: string);
    export modify-packet: func(ctx: modify-context, pkt: packet, cfg: config-view) -> decision;
    export ws-script-handler: func(topic: string, payload: string) -> string;
}
